adding updates for rest api
sensiml/simple-streaming-gateway pull request #3
Opened 2021-01-21 01:26 UTC by cdknorow

allow cors

updates

updating libary

initial config component

updating ui

update config

asdfa

removing stuff

asdfa

remove templates

adding in teset build

update list device respponse

fix pathh

asdf

asdfa

asdfa

asdfa

update test list device

minor refactor

asdfa

asdfa

asdfas

asdfas

asdfa

asdfa

asdfa

update stuff

uppdate some stuff

2021-01-21 23:16 UTC, jublin requested changes

2021-01-21 23:22 UTC, jublin commented
Should also ignore the cache files, etc.

2021-01-22 00:20 UTC, cdknorow commented on requirements.txt
> +flask-cors
added

2021-01-22 00:20 UTC, cdknorow commented on sources/serial.py
>  BAUD_RATE = 921600
good idea, for now I'm going to just add a note in the README about configuring the BAUD RATE

2021-01-22 02:35 UTC, merged